### ISSUE TITLE
how to submit the sequence of the target protein to the model

### ISSUE THREAD

**Issue by tutuxiong2024** [kyegomez/AlphaFold3#16]
Thanks a lot for your work.
May I ask a naive question on how to submit the sequence of the target protein to the model? Kind for your reply

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/AlphaFold3/issues/16">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/AlphaFold3/issues/16/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/AlphaFold3/issues/16/pledge.svg">
</picture>
</a>

**Comment by stianale** [comment]
Same here. :p I have no clue what this repo even attempts to do
