### ISSUE TITLE
[BUG] another local installation problem from openfold: ModuleNotFoundError: No module named 'scripts' .

### ISSUE THREAD

**Issue by rytakahashi** [kyegomez/AlphaFold3#6]
I had the same issue [#2](https://github.com/kyegomez/AlphaFold3/issues/2), however, when I installed torch+cu117 manually, 
```
pip install -U torch==2.0.0+cu117 torchtext==0.15.1 --extra-index-url https://download.pytorch.org/whl/cu117
```
this problem was gone.

However, now, I am seeing the different problem,

```
pip install alphafold3
Collecting alphafold3
  Using cached alphafold3-0.0.4-py3-none-any.whl.metadata (4.9 kB)
Collecting einops (from alphafold3)
  Using cached einops-0.8.0-py3-none-any.whl.metadata (12 kB)
Collecting openfold (from alphafold3)
  Using cached openfold-0.0.1.tar.gz (164 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-8nl_52c_/openfold_e8ccf631ed2748ad8eff0a1e6a8da60b/setup.py", line 21, in <module>
          from scripts.utils import get_nvidia_cc
      ModuleNotFoundError: No module named 'scripts'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
with python3.10 (or higher version) showing up when I try to install openfold alone.

Many Thanks,

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/AlphaFold3/issues/6">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/AlphaFold3/issues/6/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/AlphaFold3/issues/6/pledge.svg">
</picture>
</a>

**Comment by rytakahashi** [comment]
ah, sorry, never mind.

```
pip install -r requirements.txt 
```
solved the problem,

Many thanks,

**Comment by colbyford** [comment]
If others have this issue that won't resolve by installing from the `requirements.txt` file, you can also install a newer version from GitHub with pip:
```bash
pip install git+https://github.com/aqlaboratory/openfold
```

(The issue is due to the fact that the `openfold` PyPI entry only has v0.0.1 available to `pip install`.)
